// DO NOT EDIT: This file is autogenerated by https://github.com/0x51-dev/upeg.
package abnf

import (
	"github.com/0x51-dev/upeg/parser/op"
)

var (
	JsonPointer         = op.Capture{Name: "JsonPointer", Value: op.ZeroOrMore{Value: op.And{'/', ReferenceToken}}}
	ReferenceToken      = op.Capture{Name: "ReferenceToken", Value: op.ZeroOrMore{Value: op.Or{Unescaped, Escaped}}}
	Unescaped           = op.Or{op.RuneRange{Min: 0x00, Max: 0x2E}, op.RuneRange{Min: 0x30, Max: 0x7D}, op.RuneRange{Min: 0x7F, Max: 0xFFFC}, op.RuneRange{Min: 0xFFFE, Max: 0x10FFFF}}
	Escaped             = op.And{'~', op.Or{'0', '1'}}
	RelativeJsonPointer = op.Capture{Name: "RelativeJsonPointer", Value: op.And{OriginSpecification, op.Or{'#', JsonPointer}}}
	OriginSpecification = op.Capture{Name: "OriginSpecification", Value: op.And{NonNegativeInteger, op.Optional{Value: IndexManipulation}}}
	IndexManipulation   = op.Capture{Name: "IndexManipulation", Value: op.And{op.Or{'+', '-'}, PositiveInteger}}
	NonNegativeInteger  = op.Capture{Name: "NonNegativeInteger", Value: op.Or{'0', PositiveInteger}}
	PositiveInteger     = op.And{op.RuneRange{Min: 0x31, Max: 0x39}, op.ZeroOrMore{Value: op.RuneRange{Min: 0x30, Max: 0x39}}}
)
